server:
  port: 8766
spring:
  application:
    name: job
  #mvc:
    #view:
      #prefix: /WEB-INF/view/
      #suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cuiliying?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root